services:
  website:
    build:
      context: ./src
      dockerfile: PavelAntropov.Website/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
